name: Generate support model list

on:
  push:
    paths:
      - '**/model.json'
    branches:
      - master
  workflow_dispatch:

jobs:
  format:
    name: Generate list
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install -r ${{ github.workspace }}/.github/scripts/supported_models/requirements.txt
      - name: Pull again
        run: git pull || true
      - name: Generate file
        run: |
          python3 ${{ github.workspace }}/.github/scripts/supported_models/generate_file.py
      - uses: EndBug/add-and-commit@v7
        with:
          add: 'docs/supported_models.md'
          message: 'Update support model list'
      - uses: EndBug/add-and-commit@v7
        with:
          add: 'custom_components/data/manufacturer_device_types.json'
          message: 'Update manufacturer_device_types.json'